### ISSUE TITLE
about urls  i can't management that

### ISSUE THREAD

**Issue by liuzhixin405** [dotnet-architecture/eBooks#127]
this is a Suggest 
For some reasons, docker deployment is not used. Try to start identity.api and ordering.api to debug identityserver4
Manual setting or configuration file or command line to specify identity.api failed.
I found that the configuration file launchSettings.json of ordering.api specifies that the port of the url is 55105, but the port of IdentityUrl specified by ordering.api is 5105. But I am very confused about the port of ordering.api specified by ordering.api. And ordering.api cannot specify the start port, so it cannot be tested. There are many addresses for microservice management, and netcore specifies too many places to configure urls, so I hope to unify it to facilitate the running and testing of a single program.

**Comment by sughosneo** [comment]
Hi @liuzhixin405, thank you for reaching out. Did you get a chance to refer to the [Getting Started](https://github.com/dotnet-architecture/eShopOnContainers#getting-started) documentation? 
If you still face any challenges, please feel free to open an issue in [eShopOnContainers](https://github.com/dotnet-architecture/eShopOnContainers)

As this issue is not related to the eBooks, I am closing it as of now. But if you have any further feedback related to eBook, please feel free to reopen.
