### ISSUE TITLE
[Book Feedback]

### ISSUE THREAD

**Issue by tommymh** [dotnet-architecture/eBooks#15]
Microservices architecture

This book is amazing.  Can I get a paperback somehow?  I know I'm in the minority but I like physical books.

**Comment by nishanil** [comment]
@tommymh Thanks so much! I agree with you - physical books are cool. However, since the cloud techs are so fast changing, we constantly evaluate our approach and update the accompanying reference sample. The docs' version are also frequently updated(couple of times in a month). So, at the moment we have no plans for the print editions 😞. Sorry!
